### ISSUE TITLE
Using Laravel for the repository website

### ISSUE THREAD

**Issue by scottybo** [corePress/corePress#4]
Removed for now - we need to make sure there is a clear idea of what corePress is (with this information clearly outlined) before we move forward.

**Comment by stefanos82** [comment]
Even though I fully support Laravel, I would suggest to avoid using proprietary tools for the sake of future availability.

- How do we know nova will remain in business after an N amount of years?
- What happens to ClassicPress in case Nova it goes out of business?
- Can we guarantee that some useful features to us at this time and day will remain in use and won't be deprecated after let's say 3 years?

If we are going to use Laravel, we should set up our own infrastructure that should provide us at least a 5 years solid infrastructure.

Even if we don't choose any framework, thanks to Composer and packagist we have a huge collection of packages to choose from to set up our own infrastructure to meet our needs for the next 10 to 15 years.

**Comment by scottybo** [comment]
Removed for now - we need to make sure there is a clear idea of what corePress is (with this information clearly outlined) before we move forward.

**Comment by stefanos82** [comment]
The less stress and headaches we have on our heads, the better.

If you think Nova will be a nice service to use **for now** and at a later time to switch to something else, then by all means let's go for it.
