### ISSUE TITLE
Brand and marketing 

### ISSUE THREAD

**Issue by scottybo** [corePress/corePress#5]
Removed for now - we need to make sure there is a clear idea of what corePress is (with this information clearly outlined) before we move forward.

**Comment by stefanos82** [comment]
You did well @scottybo.

As you have said in Slack, we need to provide it a nice description that reflects the real nature of this org and repo to make things clearer to the people.

I'm open for project description and README suggestions as English is not my native language and I'm far from being fluent.

Anyone who's willing to jump in with nice suggestions, please by all means do so; your help is more than valuable.
