### ISSUE TITLE
Project description for repository and README file

### ISSUE THREAD

**Issue by stefanos82** [corePress/corePress#6]
@scottybo and @nylen any suggestions? I know Scott suggested something catchy in Slack.

Can you guys brainstorm for a short yet catchy description so I can add it to the repo's description area?

**Comment by nylen** [comment]
Nothing catchy is coming to mind.  Simple & informative is also good though.

So what actually is a concise project description?  Code shared between WordPress forks?

cc @markkap for thoughts

**Comment by stefanos82** [comment]
Project Description: "Common `core` foundations between calmPress and ClassicPress"
README: "corePress is a skeleton project that shares common core mechanisms between calmPress and ClassicPress and makes foundational collaboration between the two simpler and much more enjoyable."

How's that?

**Comment by stefanos82** [comment]
OK, I have updated README file and we need a short, yet informative description.

As soon as we come up with one, we should close this ticket.
